language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-guru' ]; then cd .. && eval "mv $currentfolder generator-guru" && cd generator-guru; fi

